In [1]:
import torch

In [2]:
x=torch.empty(5,3) # tao ma trang rong
x

tensor([[-1.2478e-11,  4.5583e-41, -1.2408e-11],
        [ 4.5583e-41, -1.2408e-11,  4.5583e-41],
        [-1.2408e-11,  4.5583e-41, -1.2408e-11],
        [ 4.5583e-41, -1.2407e-11,  4.5583e-41],
        [-1.2407e-11,  4.5583e-41, -1.2406e-11]])

In [6]:
k=torch.rand(5,3,3) # tao mot ma tran ngau nhien
k

tensor([[[0.4629, 0.1151, 0.7040],
         [0.0115, 0.7922, 0.4778],
         [0.6025, 0.7784, 0.3964]],

        [[0.0936, 0.6517, 0.5569],
         [0.3525, 0.2037, 0.4093],
         [0.8344, 0.3565, 0.7592]],

        [[0.0239, 0.6469, 0.8068],
         [0.4222, 0.6595, 0.9832],
         [0.1849, 0.4877, 0.1617]],

        [[0.4342, 0.8432, 0.5090],
         [0.9397, 0.0096, 0.3809],
         [0.4589, 0.8825, 0.7867]],

        [[0.2244, 0.8655, 0.2844],
         [0.1172, 0.4476, 0.8482],
         [0.8295, 0.5359, 0.9401]]])

In [8]:
x=torch.zeros(5,3,dtype=torch.long) # tao ma tran 0
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [10]:
x=torch.Tensor(2,2)# tao ma tran 2x2
x

tensor([[5.1077e-36, 0.0000e+00],
        [3.2954e-36, 0.0000e+00]])

In [13]:
x=torch.Tensor([4,2]) # tao ma tran 2x1
x

tensor([4., 2.])

In [12]:
x=torch.ones(5,3) # tao ma tran 1 (5x3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [15]:
y=torch.rand_like(x,dtype=torch.float) # tao ma tran ngau nhien co kieu float va co hinh dang cua x
y

tensor([0.6536, 0.8327])

In [17]:
y.shape
#y.size()
# 2 cach lay chieu tensor

torch.Size([2])

In [19]:
z=x+y # tinh cong ma tran x va y
#z=torch.add(x,y) # tinh cong ma tran x va y
z

tensor([4.6536, 2.8327])

In [22]:
y.add_(x) # tinh cong ma tran x va y, va chuyen gia tri vao y
#y=y+x
#y+=x

tensor([4.6536, 2.8327])

In [21]:
a=torch.rand(2,2)
b=torch.rand(2,2)
c=torch.empty(2,2)
#c=a+b
#c=torch.add(a,b)
torch.add(a,b, out=c) # tinh cong a va b, va chuyen ket qua vao c
c

tensor([[0.4909, 1.0382],
        [0.1078, 1.2587]])

In [23]:
c


tensor([[0.4909, 1.0382],
        [0.1078, 1.2587]])

In [26]:
c[:,1] # lay tat ca phan tu cot thu 1


tensor([1.0382, 1.2587])

In [27]:
c[1,:] # lay tat ca phan tu hang thu 1

tensor([0.1078, 1.2587])

In [30]:
a=torch.randn(4,4)
a

tensor([[ 0.6155, -0.8019,  0.2238,  0.2526],
        [ 0.9820, -0.1754,  0.8731,  0.2326],
        [ 1.5757, -0.3154, -0.9318,  1.5673],
        [-0.2044, -0.0189, -2.0974, -0.5271]])

In [33]:

a[0:2,]# lay tat ca phan tu hang thu 0 va 1

tensor([[ 0.6155, -0.8019,  0.2238,  0.2526],
        [ 0.9820, -0.1754,  0.8731,  0.2326]])

In [34]:
a.shape # lay kich thuoc cua ma tran

torch.Size([4, 4])

In [36]:
b=a.view(16) # chuyen ma tran 4x4 thanh ma tran 16x1
b

tensor([ 0.6155, -0.8019,  0.2238,  0.2526,  0.9820, -0.1754,  0.8731,  0.2326,
         1.5757, -0.3154, -0.9318,  1.5673, -0.2044, -0.0189, -2.0974, -0.5271])

In [37]:
y=a.view(-1,8) # chuyen ma tran 4x4 thanh ma tran 2x8
y.shape

torch.Size([2, 8])

In [38]:
y

tensor([[ 0.6155, -0.8019,  0.2238,  0.2526,  0.9820, -0.1754,  0.8731,  0.2326],
        [ 1.5757, -0.3154, -0.9318,  1.5673, -0.2044, -0.0189, -2.0974, -0.5271]])

In [43]:
a=torch.randn(1)
a

tensor([-0.0735])

In [44]:
a.item()# lay gia tri cua phan tu 

-0.07354755699634552

In [47]:
a=torch.randn(3,3)
a

tensor([[-0.8782, -1.1216,  1.0363],
        [ 0.0102, -0.3146, -0.2202],
        [ 1.0510, -0.5384,  0.3375]])

In [49]:
y=a.numpy()
y[0,0]

-0.8782283

In [51]:
# tensor->array: .numpy()
import numpy as np
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [53]:
b=torch.from_numpy(a)
b
#@ array -> tensor: .tensor()
# torch.from_numpy(array)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [54]:
device=torch.cuda.is_available()
device# kiem tra may co Gpu hay khong

False

In [56]:
if torch.cuda.is_available(): # neu may co Gpu
    device = torch.device('cuda')
    y=torch.ones_like(x,device=device) #`tao ma tran 1 voi kieu cua x
    x=x.to(device) # chuyen ma tran x vao may cua Gpu
    x=x+y# tinh cong ma tran x va y
    print(x)
else:
    device = torch.device('cpu')
    print('No GPU available')

No GPU available


In [69]:
x=torch.tensor(2.0,requires_grad=True)# tao ma tran 1x3, va cho phan tu thu 0,1,2 co the thay doi
x

tensor(2., requires_grad=True)

In [70]:
y=torch.exp(x)
y

tensor(7.3891, grad_fn=<ExpBackward0>)

In [71]:
y.backward()

In [72]:
x.grad

tensor(7.3891)

torch.Tensor:

    - requires_grad: nhac nho mk co luu thong tin gradient khong

    -grad_fn: luu thonh ti ham so da duoc su dung cua tensor 

    -backward: tinh gradient cua tensor(dao ham)
    
    -grad: luu cac thong tin dao ham cua tensor