# Perceptron Learning Algorithm (PLA)
Link bài viết : https://machinelearningcoban.com/2017/01/21/perceptron/

Tư tưởng của bài toán:

    Chúng ta có hai tập dữ liệu(data) đã được gán nhãn(label) và từ hai tập dữ liệu đó khi có một 
    
    điểm dữ liệu mới ta dự đoán xem nó thuộc tập dữ liệu nào bằng cách dự đoán nhãn của nó.

    Để có thể làm được điều đó chúng ta phải tìm một ranh giới(boundary) giữa hai tập dữ liệu và 
    
    xem điểm dữ liệu cần được gán nhãn nằm về phía bên nào và ta có thể dự đoán nhãn của chúng. 
    
    Một boundary đơn giản trong không gian hai chiều là một đường thằng, không gian 3 chiều 
    
    là một mặt phẳng... Những boundary được coi là đơn giản nếu chúng có thể biểu diễn bởi các hàm số 
    
    toán học đơn giản có dạng tuyến tính. 
Bài toán Perceptron

    Bài toán Perceptron được phát biểu như sau: Cho hai class được gán nhãn, hãy tìm một đường phẳng sao cho 

    toàn bộ các điểm thuộc class 1 nằm về 1 phía, toàn bộ các điểm thuộc class 2 nằm về phía còn lại của đường 
    
    phẳng đó. Với giả định rằng tồn tại một đường phẳng như thế.

    Nếu tồn tại một đường phẳng phân chia hai class thì ta gọi hai class đó là linearly separable(có thể chia 
    
    rời). Các thuật toán classification tạo ra các boundary là các đường phẳng được gọi chung là Linear 
    
    Classifier(phân loại tuyến tính).

Mô tả toán học : 

    Cho tập điểm dữ liệu đã được gán nhãn được biểu diễn X = [x1; x2; x3; x4; ...; xn] mỗi điểm dữ liệu 
    
    được biểu trên trên một hàng. Và nhãn của chúng Y = [y1; y2; y3; ...; yn] nhãn của x1 là y1
    
    ( yi cũng được biểu diễn trên mỗi hàng). 
    
    Nhãn có 2 loại đó là yi = 1 (xi thuộc class 1 xanh) và yi = -1 (xi thuộc class 2 đỏ).

    Một cách đơn giản biểu diễn đường ranh rới dạng tuyến tính:

        f(x) = w0 + w1*x1 + w2*x2 + ...+ wd*xd ( trong không gian d chiều ) 

    Đặt w = [w0, w1, w2, w3, ..., wd]

    x = [1, x1, x2,x3,...,xd]

    Khi đó ta có : f(x) = w.T * x ( w.t là ma trận chuyển vị vị của w)

   Để đơn giản chúng ta làm thử TH d = 2.

       f(x) = w0 + w1*x1+ w2*x2 = w.T * x

       Nghiêm cần tìm là w sao cho f(x) = 0 = w.T * x

   Tính chất đường thẳng: Các điểm nằm cùng một phía với đường thẳng làm cho hàm số f(x) cùng dấu.
   Ta quy định: 

      Nếu f(x) > 0 : label(xi) = 1 và ngược lại thì label(xi) = -1

   Tổng quát hóa : Nhãn của một điểm dữ liệu x là : label(x) = sng(w.T * x) (sng là hàm xác định dấu và giả sử sng(0) = 1)

   Mục tiêu bây giờ là tìm w sao cho đường thằng chia chính xác hai class sang hai bên của đường thẳng.

   Hàm mất mát chính là số điểm bị lạc trôi sang bên class còn lại hay yi và sng( f(xi) ) khác dấu nên là yi*sng(f(xi)) = -1 

       => - yi*f(xi) = 1

       Hàm mất mát : L(w) = sum( -yi * sng(f(xi) ) với i = 1 đến N( N điểm dữ liệu ) 

   Dễ dàng nhận thấy sng(f(xi)) và f(xi) cùng dấu nhưng giá trị sẽ khác nhau nên để thuận tiện tối ưu ta dùng hàm mất mát sau đây :

       L(w) = sum( -yi * f(xi)) với i = 1,N hay L(w) = sum( -yi * w.T * xi)

  áp dụng thuật toán SGD:

      Với một điểm xi bị gán nhãn sai thì hàm mất mát là: L(w, xi, yi) = -yi* w.T * xi

      Đạo hàm : 

          L'(w, xi, yi) = -yi * xi

        Khi đó ta cập nhật wt+1 = wt - eta*(-yi * xi) = wt + eta*yi*xi ( chọn eta = 1)

        wt+1 = wt + yi*xi
        
    Cập nhật tất cả các điểm xi bị miss đến khi nào mà hết thì dừng thuật toán.
        

In [114]:
from __future__ import division, unicode_literals, print_function
import numpy as np
import matplotlib.pyplot as plt
np.random.seed(2)

means = [[2, 2], [4, 2]]
cov = [[.3, .2], [.2, .3]]

# .3 mức độ chênh lệch theo trục Ox
# .2 mức độ chênh lệch theo Oy

N = 10
X0 = np.random.multivariate_normal(means[0], cov, N)
X1 = np.random.multivariate_normal(means[1], cov, N) 


N = 10
# Mang cac du lieu
X = np.concatenate((X0,X1), axis = 0)
one = np.ones((20,1))
X = np.concatenate((one,X),axis = 1)
#Nhan
y = np.concatenate((np.ones((1, N)), -1*np.ones((1, N))), axis = 1).T
# red = 1
# blue = -1

In [ ]:
def h(w, x):    
    return np.sign( np.sum( np.diag( np.dot(w.T, x) ) ))
def myPGD(w_init, X, Y):
    w = [w_init]
    while True:
        hoanvi = np.random.permutation(20)
        for i in range(20):
            data  = np.array([X[ hoanvi[i],:]])
            label = Y[hoanvi[i],0]
            m = h(w[-1],data)
            if m  != label:
                w_new  = w[-1] + label*data
                w.append(w_new)
        kq = []
        for i in range(X.shape[0]):
            m = np.array( [ h(w[-1],data)])
            kq.append(m)
        kq = np.asanyarray(kq)
        if np.linalg.norm(y - kq) < 1e-3:
            break
    return w
w_init = np.array( [[1.73118467, 1.58160763, 0.01896191]] )

print("Gía trị tối ưu khởi tạo là : ",w_init)
w = myPGD(w_init,X, y)
print(w[-1])

# [[1.73118467]
#  [1.58160763]
#  [0.01896191]]
# [[ 3.73118467]
#  [-4.62709307]
#  [ 4.24267166]]

In [112]:
# generate data
# list of points 
import numpy as np 
import matplotlib.pyplot as plt
from scipy.spatial.distance import cdist
np.random.seed(2)

means = [[2, 2], [4, 2]]
cov = [[.3, .2], [.2, .3]]
N = 10
X0 = np.random.multivariate_normal(means[0], cov, N).T
X1 = np.random.multivariate_normal(means[1], cov, N).T

X = np.concatenate((X0, X1), axis = 1)
y = np.concatenate((np.ones((1, N)), -1*np.ones((1, N))), axis = 1)
# Xbar 
X = np.concatenate((np.ones((1, 2*N)), X), axis = 0)

print(y)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1. -1. -1. -1. -1. -1. -1. -1. -1.
  -1. -1.]]


In [101]:
def h(w, x):    
    return np.sign(np.dot(w.T, x))

def has_converged(X, y, w):    
    return np.array_equal(h(w, X), y) 

def perceptron(X, y, w_init):
    w = [w_init]
    N = X.shape[1]
    d = X.shape[0]
    mis_points = []
    while True:
        mix_id = np.random.permutation(N)
        for i in range(N):
            xi = X[:, mix_id[i]].reshape(d, 1)
            yi = y[0, mix_id[i]]
            
            if h(w[-1], xi)[0] != yi: 
                mis_points.append(mix_id[i])
                w_new = w[-1] + yi*xi 
                w.append(w_new)
                
        if has_converged(X, y, w[-1]):
            break
    return (w, mis_points)

d = X.shape[0]
w_init = np.random.randn(d, 1)
(w, m) = perceptron(X, y, w_init)
print(w_init)
print(w[-1])




[[1.73118467]
 [1.58160763]
 [0.01896191]]
[[ 3.73118467]
 [-4.62709307]
 [ 4.24267166]]
