# Neural Network
Mạng thần kinh nơ-ron nhân tạo

## Khái quát về neural network
Con người có khả năng nhận biết thế giới xung quanh thông qua việc tiếp thu các thông tin, đặc điểm của các sự vật, hiện tượng. Điển hình, khi chúng ta nhìn thấy một chiếc xe, một cái cây, chúng ta có thể ngay lập tức nhận ra chúng bằng cách nhận ra các đặc điểm chung đặc trưng cho chiếc xe hoặc cái cây. Cụ thể với chiếc xe, con người đã nhìn thấy hàng triệu chiếc xe các loại khác nhau và nhận ra những đặc điểm chung của những chiếc xe. Từ đó suy ra, mỗi vật thể nào có những đặc điểm ấy ta nói rằng đó là một chiếc xe. Đối với cái cây hay bất kỳ sự vật, hiện tượng nào, con người cũng quan sát và rút ra nhận xét như vậy.

Để có thể tạo ra các thuật toán có khả năng quan sát và rút ra đặc điểm sự vật như con người, hiện nay chưa có phương pháp nào tốt hơn là mô phỏng lại cách thức hoạt động của não người. Sơ lược qua về sinh học, thì não người bao gồm hàng tỷ các tế bào thần kinh gọi là neuron (nơ ron), các tế bào này liên kết với nhau và tạo thành một mạng lưới liên kết chặt chẽ, tất cả mọi thông tin thu được về từ năm giác quan (thị giác, khứu giác, thính giác, xúc giác, vị giác) đều được truyền qua mạng lưới các tế bào này để phân tích và đưa ra các quyết định của con người.

Thuật toán mô phỏng như vậy được gọi là Neural Network.

Tuy nhiên với năng lực xử lý tính toán của máy tính hiện nay, cũng như giới hạn về hiểu biết về não người, chúng ta chỉ có thể mô phỏng một mạng lưới rất nhỏ với cấu trúc đơn giản hơn rất nhiều so với não người.
## Perceptrons

![Perceptron Visualization](perceptrons.png)

 Perceptron là một mạng neural network đơn giản nhất. Nó chỉ có duy nhất một tế bào neuron để xử lý thông tin nhận vào từ lớp đầu vào (input layer).

Input layer là lớp nhận dữ liệu đầu vào. Ví dụ như tai chúng ta nghe âm thanh, sẽ thu lại thông tin về trường độ, cao độ, độ to thì trường độ, cao độ, độ to chính là các đầu vào $x_1, x_2, .., x_n$. Các thông tin đầu vào được gọi chung là *features* của dữ liệu.

Các thông tin $x_1, x_2, x_3, ..., x_n$ được biểu diễn thành một ma trận, và truyền tới neuron bằng cách nhân với một ma trận trọng số gọi là *weight*, các phần tử của *weight* được biểu diễn trong ảnh bằng các tham số $w_1, w_2, w_3, ..., w_n$

\begin{align*}
    \begin{bmatrix}
        x_1 & x_2 & x_3 & ... & x_n
    \end{bmatrix}
    %
    \begin{bmatrix}
        w_1 \\ 
        w_2 \\
        w_3 \\
        ... \\
        w_n
    \end{bmatrix}
    =
    \begin{bmatrix}
        x_1w_1 + x_2w_2 + x_3w_3 + ... + x_nw_n
    \end{bmatrix}
\end{align*}
## Artificial Neural Network (Multi-layer Perceptron)
Chúng ta vừa tìm hiểu khái niệm về *perception*, tuy nhiên *perception* quá đơn giản chỉ bao gồm mỗi một *neuron* duy nhất, với cấu trúc đơn giản như thế này, chúng ta chỉ có thể giải được các bài toán đơn giản, không thể mô phỏng lại não người để giải quyết các bài toán phức tạp, do đó chúng ta cần mở rộng ra thành nhiều *neuron*. Mạng bao gồm nhiều *neuron* được gọi là *multilayer perceptron* hay còn biết đến với cái tên *artificial neural network (mạng thần kinh nhân tạo)* 

![Neural Network Visualization](nn.png)

Trong hình minh họa phía trên chúng ta có thể thấy ngoài việc lớp output layer đã bổ sung thành 2 neuron, còn bổ sung thêm một hidden layer ở giữa với nhiều neuron trong một lớp.

Trong mạng neuron, người ta gọi lớp đầu tiên là *input layer* vì nó nhận *features*, còn lớp cuối là *output layer* vì nó trả lại kết quả đầu ra, còn lại tất cả các lớp ở giữa đều được gọi là *hidden layer*
## Các phương pháp huấn luyện ANN
### Feed-Forward (Huấn luyện xuôi)
Tại mỗi lớp (layer) trừ input layer sẽ nhận đầu vào là layer trước nhân với ma trận *weights* (trọng số) tương ứng, cứ như thế lớp này nhân ma trận *weights* là input của lớp sau, lan truyền như vậy đến output layer thì kết thúc
### Back-Propagation (Lan truyền ngược)
Trong lan truyền xuôi, các layer đằng trước không nhận được thông tin và không biết gì về các layer đằng sau, cụ thể là trong mô hình phía trên ta khó có thể biết được khi thay đổi ma trận *weights* của input layer thì nó ảnh gì tới output layer. Do đó người dùng đạo hàm, và áp dụng quy tắc *chuỗi đạo hàm đa biến (chain rule)* để các layer không kết nối trực tiếp như input layer và output layer có được thông tin của nhau. Và chúng ta có 2 kiểu đạo hàm là tiến và ngược. Trong khuôn khổ bài viết này, chúng ta không bàn tới đạo hàm tiến và ngược vì để phân tích và so sánh chúng ta cần hiểu biết về giải tích và khái niệm *computational graph*, tuy nhiên nhìn vào cái tên chúng ta có thể dự đoán được là thuật toán này sử dụng đạo hàm ngược. Và lí do tại sao lại sử dụng đạo hàm ngược sao? Với một hàm số 1 triệu biến, đạo ngược sẽ nhanh gấp 1 triệu lần đạo hàm tiến.

## Triển khai ANN với thư viện scikit-learn
### Chuẩn bị dữ liệu
Scikit-learn là một thư viện tính toán số học và machine learning mạnh mẽ, dễ học , dễ dùng

Ngoài ra, chúng ta còn cần một thư viện để xử lý dữ liệu, vì dữ liệu thường không ở dạng ma trận luôn, mà được viết ở các dạng chưa chuẩn như là file excel, ... Để đọc và xử lý dữ liệu, chúng ta thường sử dụng thư viện pandas.

In [1]:
# Khai báo thư viện
import sklearn
import pandas as pd

Trong bài này chúng ta sử dụng bộ dữ liệu iris là một bộ dữ liệu phân loại hoa diên vĩ dựa trên các đặc điểm về hình dạng của bông hoa.

Trước hết chúng ta tiến hành tải và nạp dữ liệu vào máy bằng thư viện pandas

Đường dẫn để tải dữ liệu

link = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

Tên các cột dữ liệu, phần này được mô tả trên website của bộ dữ liệu iris

In [ ]:
link='/home/thinh-do/Hoc_Tap/Machine_Learning_Basic/5_Binary_Classification/2.Logistic_regresion/Tự luyện/iris.csv'

In [3]:
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

Tiến hành nạp dữ liệu vào máy tính

In [4]:
dataset = pd.read_csv(link, names=names)

Ta xem thử 5 mẫu dữ liệu đầu như thế nào

In [5]:
print(dataset[:5])

   sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa


Tác giả của bộ dữ liệu này đã trộn cả class (nhãn) vào trong cùng với features, ta cần phải tách riêng nhãn và features ra

In [6]:
features = dataset.iloc[:, :4]
labels = dataset.iloc[:,4:]

In thử ra 5 mẫu dữ liệu đầu của tập features

In [7]:
print(features[:5])

   sepal-length  sepal-width  petal-length  petal-width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2


In thử ra 5 mẫu dữ liệu đầu của tập labels

In [8]:
print(labels[:5])

         Class
0  Iris-setosa
1  Iris-setosa
2  Iris-setosa
3  Iris-setosa
4  Iris-setosa


Tập các giá trị phân biệt của labels

In [9]:
print(labels.Class.unique())

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


Tuy nhiên, công việc xử lý dữ liệu chưa xong, chúng ta không nào đưa nhãn dưới dạng string vào mạng ANN được, cần phải ánh xạ các string đó thành số để có thể tính toán

In [10]:
from sklearn.preprocessing import LabelEncoder
labels = labels.apply(LabelEncoder().fit_transform)

Bây giờ, chúng ta lại in thử ra 5 mẫu dữ liệu đầu của labels

In [11]:
print(labels[:5])

   Class
0      0
1      0
2      0
3      0
4      0


Các giá trị phân biệt của labels

In [12]:
print(labels.Class.unique())

[0 1 2]


Như vậy chúng ta đã tiến hành ánh xạ thành công từ kiểu dữ liệu string sang thành số để có thế tính toán được.

Thông thường, chúng ta có một bộ dữ liệu lớn thì phải chia thành 2 phần: training và validation.

Trong quá trình training chúng ta để nguyên bộ validation, sau khi train xong, chúng sẽ sử dụng bộ validation như một bài kiểm tra để đánh giá độ hiệu quả của model, và tỉ lệ thông thường sẽ là chia 5, bộ train 4, bộ validation 1

In [13]:
from sklearn.model_selection import train_test_split
features_train, features_valid, labels_train, labels_valid = train_test_split(features, labels, test_size = 0.20)

Ngoài ra còn một kỹ thuật được gọi là *Feature Scaling*

Nếu giá trị giữa các feature của chúng ta lệch nhau lớn, sẽ làm cho đồ thị của chúng bị rất méo, khiến quá trình training khó hội tụ. Do đó người ta thường chỉnh lại để làm sao miền giá trị của các cột tương đương nhau, khiến đồ thị đều, nhanh hội tụ

In [14]:
from sklearn.preprocessing import StandardScaler  
scaler = StandardScaler()  
scaler.fit(features_train)

features_train = scaler.transform(features_train)
features_valid = scaler.transform(features_valid)

Bây giờ ta thử quan lại 5 mẫu dữ liệu ban đầu một lần nữa

In [15]:
print(features_train[:5])

[[ 1.0295396   0.03726262  1.04885915  1.61353854]
 [-1.00757077  0.26083837 -1.40918627 -1.28030775]
 [-1.00757077  0.70798987 -1.18572759 -1.01723082]
 [-0.88774075  1.60229286 -1.18572759 -1.28030775]
 [-1.24723081  0.70798987 -1.18572759 -1.28030775]]


Như vậy dữ liệu của chúng ta đã chuyển sang dạng ma trận, và có miền giá trị tương đương nhau, không lệch như ban đầu
### Huấn luyện và phục vụ model

In [16]:
from sklearn.neural_network import MLPClassifier  

Chúng ta sẽ sử dụng 3 hiden layers, lớp hidden thứ nhất gồm 10 neuron, lớp thứ 2 gồm 7 neuron và lớp thứ 3 gồm 5 neuron. Input và output sẽ được tự động nhận diện để điều chỉnh kích thước. max_iter là số lần huấn luyện, ở đây chúng ta huấn luyện 2000 lần

In [17]:
mlp = MLPClassifier(hidden_layer_sizes=(10, 7, 5), max_iter=2000)  

Ngoài ra nếu chúng ta để ý thì hiện nay labels train đang ở dạng ma trận 2 chiều, và chúng buộc phải kéo nó sang dạng mảng 1 chiều. Để kéo một ma trận 2 chiều sang dạng mảng 1 chiều, ta sử dụng phương thức numpy.ndarray.ravel(). Lí do tại chúng ta dùng pandas để nạp dữ liệu, mà bây giờ lại dùng numpy để chuẩn hóa dữ liệu, đó vì pandas ngầm sử dụng numpy để lưu dữ liệu các tensor.

Bây giờ chúng ta tiến hành đập phẳng ma trận 2 chiều sang dạng mảng 1 chiều

In [18]:
labels_train_1d = labels_train.values.ravel()
labels_valid_1d = labels_valid.values.ravel()

In [19]:
mlp.fit(features_train, labels_train_1d) 

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(10, 7, 5), learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

Chúng ta tiến hành chạy thử model với tâp validation

In [20]:
predictions = mlp.predict(features_valid)  

In ra kết quả chạy thử với tập validation

In [21]:
print(predictions)

[1 0 2 2 0 0 1 1 0 2 1 0 1 2 2 0 0 1 1 0 2 2 2 1 2 2 1 1 1 2]


### Đánh giá model
Đối với dạng bài classification, người ta thường hay dùng accuracy score làm thước đo (metric)

In [22]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(labels_valid_1d, predictions)
print("Accuracy của model: {}%".format(round(accuracy*100,2)))

Accuracy của model: 96.67%
